export const MenuActionId = {
  AppAbout: 'app:about',
  AppPreferences: 'app:preferences',
  AppQuit: 'app:quit',
  FileOpen: 'file:open',
  FileClose: 'file:close',
  EditUndo: 'edit:undo',
  EditRedo: 'edit:redo',
  ViewReload: 'view:reload',
  ViewToggleDevTools: 'view:toggle-devtools',
  ViewToggleFullScreen: 'view:toggle-fullscreen',
  PlaybackToggle: 'playback:toggle',
  PlaybackNext: 'playback:next',
  PlaybackPrev: 'playback:prev',
  PlaybackSeekForward: 'playback:seek-forward',
  PlaybackSeekBackward: 'playback:seek-backward',
  WindowMinimize: 'window:minimize',
  WindowClose: 'window:close',
  HelpDocs: 'help:docs',
  HelpReportIssue: 'help:report-issue',
  DevOpenUserData: 'dev:open-user-data',
  DevOpenCache: 'dev:open-cache',
  DevOpenLogs: 'dev:open-logs',
  DevClearStore: 'dev:clear-store',
  DevShowConfigWindow: 'dev:show-config-window',
  DevResetServerUrl: 'dev:reset-server-url',
} as const;

export type MenuActionIdType = (typeof MenuActionId)[keyof typeof MenuActionId];
