import { MovieResource } from '@/modules/library-movies/modes.ts';

export const movieResources: MovieResource[] = [
  {
    title: "The Shawshank Redemption",
    ratingScores: [{ provider: "IMDb", score: "9.3" }, { provider: "Rotten Tomatoes", score: "91%" }],
    status: "OK",
    runtime: "142 minutes",
    language: "English",
    year: 1994,
    summary: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    genres: ["Drama"],
    actors: [{ name: "Tim Robbins" }, { name: "Morgan Freeman" }]
  },
  {
    title: "The Godfather",
    ratingScores: [{ provider: "IMDb", score: "9.2" }, { provider: "Rotten Tomatoes", score: "97%" }],
    status: "OK",
    runtime: "175 minutes",
    language: "English",
    year: 1972,
    summary: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    genres: ["Crime", "Drama"],
    actors: [{ name: "Marlon Brando" }, { name: "Al Pacino" }]
  },
  {
    title: "The Dark Knight",
    ratingScores: [{ provider: "IMDb", score: "9.0" }, { provider: "Rotten Tomatoes", score: "94%" }],
    status: "OK",
    runtime: "152 minutes",
    language: "English",
    year: 2008,
    summary: "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
    genres: ["Action", "Crime", "Drama"],
    actors: [{ name: "Christian Bale" }, { name: "Heath Ledger" }]
  },
  {
    title: "Pulp Fiction",
    ratingScores: [{ provider: "IMDb", score: "8.9" }, { provider: "Rotten Tomatoes", score: "92%" }],
    status: "OK",
    runtime: "154 minutes",
    language: "English",
    year: 1994,
    summary: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    genres: ["Crime", "Drama"],
    actors: [{ name: "John Travolta" }, { name: "Uma Thurman" }]
  },
  {
    title: "Inception",
    ratingScores: [{ provider: "IMDb", score: "8.8" }, { provider: "Rotten Tomatoes", score: "87%" }],
    status: "OK",
    runtime: "148 minutes",
    language: "English",
    year: 2010,
    summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    actors: [{ name: "Leonardo DiCaprio" }, { name: "Joseph Gordon-Levitt" }]
  },
  {
    title: "Fight Club",
    ratingScores: [{ provider: "IMDb", score: "8.8" }, { provider: "Rotten Tomatoes", score: "79%" }],
    status: "OK",
    runtime: "139 minutes",
    language: "English",
    year: 1999,
    summary: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.",
    genres: ["Drama"],
    actors: [{ name: "Brad Pitt" }, { name: "Edward Norton" }]
  },
  {
    title: "Forrest Gump",
    ratingScores: [{ provider: "IMDb", score: "8.8" }, { provider: "Rotten Tomatoes", score: "71%" }],
    status: "OK",
    runtime: "142 minutes",
    language: "English",
    year: 1994,
    summary: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    genres: ["Drama", "Romance"],
    actors: [{ name: "Tom Hanks" }, { name: "Robin Wright" }]
  },
  {
    title: "The Matrix",
    ratingScores: [{ provider: "IMDb", score: "8.7" }, { provider: "Rotten Tomatoes", score: "88%" }],
    status: "OK",
    runtime: "136 minutes",
    language: "English",
    year: 1999,
    summary: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    genres: ["Action", "Sci-Fi"],
    actors: [{ name: "Keanu Reeves" }, { name: "Laurence Fishburne" }]
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    ratingScores: [{ provider: "IMDb", score: "8.8" }, { provider: "Rotten Tomatoes", score: "91%" }],
    status: "OK",
    runtime: "178 minutes",
    language: "English",
    year: 2001,
    summary: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    genres: ["Action", "Adventure", "Drama"],
    actors: [{ name: "Elijah Wood" }, { name: "Ian McKellen" }]
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    ratingScores: [{ provider: "IMDb", score: "8.7" }, { provider: "Rotten Tomatoes", score: "94%" }],
    status: "OK",
    runtime: "124 minutes",
    language: "English",
    year: 1980,
    summary: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
    genres: ["Action", "Adventure", "Fantasy"],
    actors: [{ name: "Mark Hamill" }, { name: "Harrison Ford" }]
  },
  {
    title: "Interstellar",
    ratingScores: [{ provider: "IMDb", score: "8.6" }, { provider: "Rotten Tomatoes", score: "72%" }],
    status: "OK",
    runtime: "169 minutes",
    language: "English",
    year: 2014,
    summary: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    actors: [{ name: "Matthew McConaughey" }, { name: "Anne Hathaway" }]
  },
  {
    title: "The Silence of the Lambs",
    ratingScores: [{ provider: "IMDb", score: "8.6" }, { provider: "Rotten Tomatoes", score: "96%" }],
    status: "OK",
    runtime: "118 minutes",
    language: "English",
    year: 1991,
    summary: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    genres: ["Crime", "Drama", "Thriller"],
    actors: [{ name: "Jodie Foster" }, { name: "Anthony Hopkins" }]
  },
  {
    title: "Saving Private Ryan",
    ratingScores: [{ provider: "IMDb", score: "8.6" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "169 minutes",
    language: "English",
    year: 1998,
    summary: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    genres: ["Drama", "War"],
    actors: [{ name: "Tom Hanks" }, { name: "Matt Damon" }]
  },
  {
    title: "The Green Mile",
    ratingScores: [{ provider: "IMDb", score: "8.6" }, { provider: "Rotten Tomatoes", score: "79%" }],
    status: "OK",
    runtime: "189 minutes",
    language: "English",
    year: 1999,
    summary: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    genres: ["Crime", "Drama", "Fantasy"],
    actors: [{ name: "Tom Hanks" }, { name: "Michael Clarke Duncan" }]
  },
  {
    title: "Parasite",
    ratingScores: [{ provider: "IMDb", score: "8.6" }, { provider: "Rotten Tomatoes", score: "98%" }],
    status: "OK",
    runtime: "132 minutes",
    language: "Korean",
    year: 2019,
    summary: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    genres: ["Comedy", "Drama", "Thriller"],
    actors: [{ name: "Kang-ho Song" }, { name: "Sun-kyun Lee" }]
  },
  {
    title: "Spirited Away",
    ratingScores: [{ provider: "IMDb", score: "8.6" }, { provider: "Rotten Tomatoes", score: "97%" }],
    status: "OK",
    runtime: "125 minutes",
    language: "Japanese",
    year: 2001,
    summary: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
    genres: ["Animation", "Adventure", "Family"],
    actors: [{ name: "Daveigh Chase" }, { name: "Suzanne Pleshette" }]
  },
  {
    title: "The Lion King",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "88 minutes",
    language: "English",
    year: 1994,
    summary: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    genres: ["Animation", "Adventure", "Drama"],
    actors: [{ name: "Matthew Broderick" }, { name: "Jeremy Irons" }]
  },
  {
    title: "The Pianist",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "95%" }],
    status: "OK",
    runtime: "150 minutes",
    language: "English",
    year: 2002,
    summary: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    genres: ["Biography", "Drama", "Music"],
    actors: [{ name: "Adrien Brody" }, { name: "Thomas Kretschmann" }]
  },
  {
    title: "The Usual Suspects",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "89%" }],
    status: "OK",
    runtime: "106 minutes",
    language: "English",
    year: 1995,
    summary: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which begin when five criminals meet at a seemingly random police lineup.",
    genres: ["Crime", "Drama", "Mystery"],
    actors: [{ name: "Kevin Spacey" }, { name: "Gabriel Byrne" }]
  },

  {
    title: "Terminator 2: Judgment Day",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "137 minutes",
    language: "English",
    year: 1991,
    summary: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.",
    genres: ["Action", "Sci-Fi"],
    actors: [{ name: "Arnold Schwarzenegger" }, { name: "Linda Hamilton" }]
  },
  {
    title: "Back to the Future",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "96%" }],
    status: "OK",
    runtime: "116 minutes",
    language: "English",
    year: 1985,
    summary: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, eccentric scientist Doc Brown.",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    actors: [{ name: "Michael J. Fox" }, { name: "Christopher Lloyd" }]
  },
  {
    title: "Gladiator",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "77%" }],
    status: "OK",
    runtime: "155 minutes",
    language: "English",
    year: 2000,
    summary: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    genres: ["Action", "Adventure", "Drama"],
    actors: [{ name: "Russell Crowe" }, { name: "Joaquin Phoenix" }]
  },
  {
    title: "Green Book",
    ratingScores: [{ provider: "IMDb", score: "8.2" }, { provider: "Rotten Tomatoes", score: "77%" }],
    status: "OK",
    runtime: "130 minutes",
    language: "English",
    year: 2018,
    summary: "A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour of venues through the 1960s American South.",
    genres: ["Biography", "Comedy", "Drama"],
    actors: [{ name: "Viggo Mortensen" }, { name: "Mahershala Ali" }]
  },
  {
    title: "Hamilton",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "98%" }],
    status: "OK",
    runtime: "160 minutes",
    language: "English",
    year: 2020,
    summary: "The real life of one of America's foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.",
    genres: ["Biography", "Drama", "History"],
    actors: [{ name: "Lin-Manuel Miranda" }, { name: "Phillipa Soo" }]
  },
  {
    title: "Blade Runner 2049",
    ratingScores: [{ provider: "IMDb", score: "8.0" }, { provider: "Rotten Tomatoes", score: "88%" }],
    status: "OK",
    runtime: "164 minutes",
    language: "English",
    year: 2017,
    summary: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    genres: ["Action", "Drama", "Sci-Fi"],
    actors: [{ name: "Harrison Ford" }, { name: "Ryan Gosling" }]
  },
  {
    title: "A Beautiful Mind",
    ratingScores: [{ provider: "IMDb", score: "8.2" }, { provider: "Rotten Tomatoes", score: "74%" }],
    status: "OK",
    runtime: "135 minutes",
    language: "English",
    year: 2001,
    summary: "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.",
    genres: ["Biography", "Drama"],
    actors: [{ name: "Russell Crowe" }, { name: "Ed Harris" }]
  },
  {
    title: "Room",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "118 minutes",
    language: "English",
    year: 2015,
    summary: "A young boy is raised within the confines of a small shed.",
    genres: ["Drama", "Thriller"],
    actors: [{ name: "Brie Larson" }, { name: "Jacob Tremblay" }]
  },
  {
    title: "The Shape of Water",
    ratingScores: [{ provider: "IMDb", score: "7.3" }, { provider: "Rotten Tomatoes", score: "92%" }],
    status: "OK",
    runtime: "123 minutes",
    language: "English",
    year: 2017,
    summary: "At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.",
    genres: ["Drama", "Fantasy", "Romance"],
    actors: [{ name: "Sally Hawkins" }, { name: "Octavia Spencer" }]
  },
  {
    title: "The Prestige",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "76%" }],
    status: "OK",
    runtime: "130 minutes",
    language: "English",
    year: 2006,
    summary: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    actors: [{ name: "Christian Bale" }, { name: "Hugh Jackman" }]
  },
  {
    title: "Whiplash",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "94%" }],
    status: "OK",
    runtime: "106 minutes",
    language: "English",
    year: 2014,
    summary: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    genres: ["Drama", "Music"],
    actors: [{ name: "Miles Teller" }, { name: "J.K. Simmons" }]
  },
  {
    title: "The Intouchables",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "75%" }],
    status: "OK",
    runtime: "112 minutes",
    language: "French",
    year: 2011,
    summary: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
    genres: ["Biography", "Comedy", "Drama"],
    actors: [{ name: "François Cluzet" }, { name: "Omar Sy" }]
  },
  {
    title: "The Great Dictator",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "125 minutes",
    language: "English",
    year: 1940,
    summary: "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
    genres: ["Comedy", "Drama", "War"],
    actors: [{ name: "Charlie Chaplin" }, { name: "Paulette Goddard" }]
  },
  {
    title: "The Pianist",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "95%" }],
    status: "OK",
    runtime: "150 minutes",
    language: "English",
    year: 2002,
    summary: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    genres: ["Biography", "Drama", "Music"],
    actors: [{ name: "Adrien Brody" }, { name: "Thomas Kretschmann" }]
  },
  {
    title: "The Usual Suspects",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "89%" }],
    status: "OK",
    runtime: "106 minutes",
    language: "English",
    year: 1995,
    summary: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which begin when five criminals meet at a seemingly random police lineup.",
    genres: ["Crime", "Drama", "Mystery"],
    actors: [{ name: "Kevin Spacey" }, { name: "Gabriel Byrne" }]
  },
  {
    title: "Terminator 2: Judgment Day",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "137 minutes",
    language: "English",
    year: 1991,
    summary: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.",
    genres: ["Action", "Sci-Fi"],
    actors: [{ name: "Arnold Schwarzenegger" }, { name: "Linda Hamilton" }]
  },
  {
    title: "Back to the Future",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "96%" }],
    status: "OK",
    runtime: "116 minutes",
    language: "English",
    year: 1985,
    summary: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, eccentric scientist Doc Brown.",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    actors: [{ name: "Michael J. Fox" }, { name: "Christopher Lloyd" }]
  },
  {
    title: "Gladiator",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "77%" }],
    status: "OK",
    runtime: "155 minutes",
    language: "English",
    year: 2000,
    summary: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    genres: ["Action", "Adventure", "Drama"],
    actors: [{ name: "Russell Crowe" }, { name: "Joaquin Phoenix" }]
  },
  {
    title: "Memento",
    ratingScores: [{ provider: "IMDb", score: "8.4" }, { provider: "Rotten Tomatoes", score: "93%" }],
    status: "OK",
    runtime: "113 minutes",
    language: "English",
    year: 2000,
    summary: "A man with short-term memory loss attempts to track down his wife's murderer.",
    genres: ["Mystery", "Thriller"],
    actors: [{ name: "Guy Pearce" }, { name: "Carrie-Anne Moss" }]
  },
  {
    title: "The Departed",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "90%" }],
    status: "OK",
    runtime: "151 minutes",
    language: "English",
    year: 2006,
    summary: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    genres: ["Crime", "Drama", "Thriller"],
    actors: [{ name: "Leonardo DiCaprio" }, { name: "Matt Damon" }]
  },
  {
    title: "American History X",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "83%" }],
    status: "OK",
    runtime: "119 minutes",
    language: "English",
    year: 1998,
    summary: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
    genres: ["Drama"],
    actors: [{ name: "Edward Norton" }, { name: "Edward Furlong" }]
  },
  {
    title: "Psycho",
    ratingScores: [{ provider: "IMDb", score: "8.5" }, { provider: "Rotten Tomatoes", score: "96%" }],
    status: "OK",
    runtime: "109 minutes",
    language: "English",
    year: 1960,
    summary: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.",
    genres: ["Horror", "Mystery", "Thriller"],
    actors: [{ name: "Anthony Perkins" }, { name: "Janet Leigh" }]
  },
  {
    title: "The Incredibles",
    ratingScores: [{ provider: "IMDb", score: "8.0" }, { provider: "Rotten Tomatoes", score: "97%" }],
    status: "OK",
    runtime: "115 minutes",
    language: "English",
    year: 2004,
    summary: "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.",
    genres: ["Animation", "Action", "Adventure"],
    actors: [{ name: "Craig T. Nelson" }, { name: "Holly Hunter" }]
  },
  {
    title: "Up",
    ratingScores: [{ provider: "IMDb", score: "8.2" }, { provider: "Rotten Tomatoes", score: "98%" }],
    status: "OK",
    runtime: "96 minutes",
    language: "English",
    year: 2009,
    summary: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.",
    genres: ["Animation", "Adventure", "Drama"],
    actors: [{ name: "Edward Asner" }, { name: "Jordan Nagai" }]
  },
  {
    title: "Coco",
    ratingScores: [{ provider: "IMDb", score: "8.4" }, { provider: "Rotten Tomatoes", score: "97%" }],
    status: "OK",
    runtime: "105 minutes",
    language: "English",
    year: 2017,
    summary: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    genres: ["Animation", "Adventure", "Family"],
    actors: [{ name: "Anthony Gonzalez" }, { name: "Gael García Bernal" }]
  },
  {
    title: "La La Land",
    ratingScores: [{ provider: "IMDb", score: "8.0" }, { provider: "Rotten Tomatoes", score: "91%" }],
    status: "OK",
    runtime: "128 minutes",
    language: "English",
    year: 2016,
    summary: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    genres: ["Comedy", "Drama", "Music"],
    actors: [{ name: "Ryan Gosling" }, { name: "Emma Stone" }]
  },
  {
    title: "Inside Out",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "98%" }],
    status: "OK",
    runtime: "95 minutes",
    language: "English",
    year: 2015,
    summary: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust, and Sadness - conflict on how best to navigate a new city, house, and school.",
    genres: ["Animation", "Adventure", "Comedy"],
    actors: [{ name: "Amy Poehler" }, { name: "Bill Hader" }]
  },
  {
    title: "Toy Story",
    ratingScores: [{ provider: "IMDb", score: "8.3" }, { provider: "Rotten Tomatoes", score: "100%" }],
    status: "OK",
    runtime: "81 minutes",
    language: "English",
    year: 1995,
    summary: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
    genres: ["Animation", "Adventure", "Comedy"],
    actors: [{ name: "Tom Hanks" }, { name: "Tim Allen" }]
  },
  {
    title: "Shrek",
    ratingScores: [{ provider: "IMDb", score: "7.9" }, { provider: "Rotten Tomatoes", score: "88%" }],
    status: "OK",
    runtime: "90 minutes",
    language: "English",
    year: 2001,
    summary: "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
    genres: ["Animation", "Adventure", "Comedy"],
    actors: [{ name: "Mike Myers" }, { name: "Eddie Murphy" }]
  },
  {
    title: "The Bourne Identity",
    ratingScores: [{ provider: "IMDb", score: "7.9" }, { provider: "Rotten Tomatoes", score: "83%" }],
    status: "OK",
    runtime: "119 minutes",
    language: "English",
    year: 2002,
    summary: "A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.",
    genres: ["Action", "Mystery", "Thriller"],
    actors: [{ name: "Matt Damon" }, { name: "Franka Potente" }]
  },
  {
    title: "Gone Girl",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "87%" }],
    status: "OK",
    runtime: "149 minutes",
    language: "English",
    year: 2014,
    summary: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    genres: ["Drama", "Mystery", "Thriller"],
    actors: [{ name: "Ben Affleck" }, { name: "Rosamund Pike" }]
  },
  {
    title: "The Social Network",
    ratingScores: [{ provider: "IMDb", score: "7.7" }, { provider: "Rotten Tomatoes", score: "96%" }],
    status: "OK",
    runtime: "120 minutes",
    language: "English",
    year: 2010,
    summary: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.",
    genres: ["Biography", "Drama"],
    actors: [{ name: "Jesse Eisenberg" }, { name: "Andrew Garfield" }]
  },
  {
    title: "The Grand Budapest Hotel",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "91%" }],
    status: "OK",
    runtime: "99 minutes",
    language: "English",
    year: 2014,
    summary: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
    genres: ["Adventure", "Comedy", "Crime"],
    actors: [{ name: "Ralph Fiennes" }, { name: "F. Murray Abraham" }]
  },
  {
    title: "Mad Max: Fury Road",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "97%" }],
    status: "OK",
    runtime: "120 minutes",
    language: "English",
    year: 2015,
    summary: "In a post-apocalyptic wasteland, Max helps a rebellious woman and a group of female prisoners escape from an oppressive warlord and his army in an armored tanker truck.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    actors: [{ name: "Tom Hardy" }, { name: "Charlize Theron" }]
  },
  {
    title: "The Wolf of Wall Street",
    ratingScores: [{ provider: "IMDb", score: "8.2" }, { provider: "Rotten Tomatoes", score: "79%" }],
    status: "OK",
    runtime: "180 minutes",
    language: "English",
    year: 2013,
    summary: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption, and the federal government.",
    genres: ["Biography", "Crime", "Drama"],
    actors: [{ name: "Leonardo DiCaprio" }, { name: "Jonah Hill" }]
  },
  {
    title: "The Hateful Eight",
    ratingScores: [{ provider: "IMDb", score: "7.8" }, { provider: "Rotten Tomatoes", score: "75%" }],
    status: "OK",
    runtime: "168 minutes",
    language: "English",
    year: 2015,
    summary: "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
    genres: ["Crime", "Drama", "Mystery"],
    actors: [{ name: "Samuel L. Jackson" }, { name: "Kurt Russell" }]
  },
  {
    title: "Birdman",
    ratingScores: [{ provider: "IMDb", score: "7.7" }, { provider: "Rotten Tomatoes", score: "91%" }],
    status: "OK",
    runtime: "119 minutes",
    language: "English",
    year: 2014,
    summary: "A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.",
    genres: ["Comedy", "Drama"],
    actors: [{ name: "Michael Keaton" }, { name: "Zach Galifianakis" }]
  },
  {
    title: "12 Years a Slave",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "95%" }],
    status: "OK",
    runtime: "134 minutes",
    language: "English",
    year: 2013,
    summary: "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.",
    genres: ["Biography", "Drama", "History"],
    actors: [{ name: "Chiwetel Ejiofor" }, { name: "Michael Kenneth Williams" }]
  },
  {
    title: "Django Unchained",
    ratingScores: [{ provider: "IMDb", score: "8.4" }, { provider: "Rotten Tomatoes", score: "87%" }],
    status: "OK",
    runtime: "165 minutes",
    language: "English",
    year: 2012,
    summary: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.",
    genres: ["Drama", "Western"],
    actors: [{ name: "Jamie Foxx" }, { name: "Christoph Waltz" }]
  },
  {
    title: "Moonlight",
    ratingScores: [{ provider: "IMDb", score: "7.4" }, { provider: "Rotten Tomatoes", score: "98%" }],
    status: "OK",
    runtime: "111 minutes",
    language: "English",
    year: 2016,
    summary: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.",
    genres: ["Drama"],
    actors: [{ name: "Mahershala Ali" }, { name: "Naomie Harris" }]
  },
  {
    title: "Spotlight",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "97%" }],
    status: "OK",
    runtime: "129 minutes",
    language: "English",
    year: 2015,
    summary: "The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.",
    genres: ["Biography", "Crime", "Drama"],
    actors: [{ name: "Mark Ruffalo" }, { name: "Michael Keaton" }]
  },
  {
    title: "Argo",
    ratingScores: [{ provider: "IMDb", score: "7.7" }, { provider: "Rotten Tomatoes", score: "96%" }],
    status: "OK",
    runtime: "120 minutes",
    language: "English",
    year: 2012,
    summary: "Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1979.",
    genres: ["Biography", "Drama", "Thriller"],
    actors: [{ name: "Ben Affleck" }, { name: "Bryan Cranston" }]
  },
  {
    title: "The Revenant",
    ratingScores: [{ provider: "IMDb", score: "8.0" }, { provider: "Rotten Tomatoes", score: "78%" }],
    status: "OK",
    runtime: "156 minutes",
    language: "English",
    year: 2015,
    summary: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
    genres: ["Action", "Adventure", "Drama"],
    actors: [{ name: "Leonardo DiCaprio" }, { name: "Tom Hardy" }]
  },
  {
    title: "Slumdog Millionaire",
    ratingScores: [{ provider: "IMDb", score: "8.0" }, { provider: "Rotten Tomatoes", score: "91%" }],
    status: "OK",
    runtime: "120 minutes",
    language: "English",
    year: 2008,
    summary: "A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of 'Who Wants to Be a Millionaire?'.",
    genres: ["Drama", "Romance"],
    actors: [{ name: "Dev Patel" }, { name: "Freida Pinto" }]
  },
  {
    title: "The Artist",
    ratingScores: [{ provider: "IMDb", score: "7.9" }, { provider: "Rotten Tomatoes", score: "95%" }],
    status: "OK",
    runtime: "100 minutes",
    language: "English",
    year: 2011,
    summary: "An egomaniacal film star develops a relationship with a young dancer against the backdrop of Hollywood's silent era.",
    genres: ["Comedy", "Drama", "Romance"],
    actors: [{ name: "Jean Dujardin" }, { name: "Bérénice Bejo" }]
  },
  {
    title: "Hacksaw Ridge",
    ratingScores: [{ provider: "IMDb", score: "8.1" }, { provider: "Rotten Tomatoes", score: "85%" }],
    status: "OK",
    runtime: "139 minutes",
    language: "English",
    year: 2016,
    summary: "World War II American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people, and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
    genres: ["Biography", "Drama", "History"],
    actors: [{ name: "Andrew Garfield" }, { name: "Sam Worthington" }]
  },
  {
    title: "Her",
    ratingScores: [{ provider: "IMDb", score: "8.0" }, { provider: "Rotten Tomatoes", score: "94%" }],
    status: "OK",
    runtime: "126 minutes",
    language: "English",
    year: 2013,
    summary: "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
    genres: ["Drama", "Romance", "Sci-Fi"],
    actors: [{ name: "Joaquin Phoenix" }, { name: "Amy Adams" }]
  },
];