import { test, expect } from '@playwright/test'

test('disabled stores isolate renders; enabled UI traces, exports and disables recording', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('selection')).toHaveText('none')
  await page.getByRole('button', { name: 'Change view', exact: true }).click()
  await expect(page.getByTestId('selection-renders')).toHaveText('1')
  await page.getByRole('button', { name: 'Select album', exact: true }).click()
  await expect(page.getByTestId('selection')).toHaveText('album-one')
  await expect(page.getByTestId('action-renders')).toHaveText('1')
  await page.getByRole('button', { name: 'Select album', exact: true }).click()
  await expect(page.getByTestId('selection-renders')).toHaveText('2')
  await page.getByRole('button', { name: 'Toggle debug panel' }).click()
  await page.getByRole('button', { name: 'Store Timeline', exact: true }).click()
  await expect(page.getByText(/Store recording is disabled/)).toBeVisible()
  await page.getByRole('button', { name: 'Enable store tracing and reload' }).click()
  await expect(page.getByTestId('selection')).toHaveText('none')
  await page.getByRole('button', { name: 'Select album', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle debug panel' }).click()
  await page.getByRole('button', { name: 'Store Timeline', exact: true }).click()
  const action = page.locator('summary').filter({ hasText: /select · action/ })
  await expect(action).toBeVisible()
  await action.click()
  await expect(action.locator('..').getByText('Call stack', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Export trace', exact: true }).click()
  const trace = JSON.parse(await page.getByRole('textbox', { name: 'Trace JSON' }).inputValue())
  expect(trace.schemaVersion).toBe(1)
  expect(trace.events.some((event: { kind: string; changedKeys?: string[] }) => event.kind === 'update' && event.changedKeys?.includes('selectedId'))).toBe(true)
  await page.getByRole('button', { name: 'Store Inspector', exact: true }).click()
  await page.getByRole('combobox', { name: 'Select store' }).click()
  await page.getByRole('option', { name: /selection/i }).click()
  await expect(page.getByText(/"selectedId": "album-one"/)).toBeVisible()
  await page.getByRole('button', { name: 'Disable store tracing and reload' }).click()
  await page.getByRole('button', { name: 'Toggle debug panel' }).click()
  await page.getByRole('button', { name: 'Store Timeline', exact: true }).click()
  await expect(page.getByText(/Store recording is disabled/)).toBeVisible()
})
