<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006250000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the failed_messages table for the listable Messenger failure transport.';
    }

    public function up(Schema $schema): void
    {
        // Column names and meanings are fixed by symfony/doctrine-messenger, which
        // runs with auto_setup disabled. Its PostgreSQL insert reads the id back with
        // RETURNING, so an identity column serves. It binds instants as UTC wall-clock
        // text, which timestamptz stores correctly in Baander's UTC sessions.
        $this->addSql(<<<'SQL'
            CREATE TABLE failed_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL,
                available_at TIMESTAMPTZ NOT NULL,
                delivered_at TIMESTAMPTZ DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        // The transport's own index, which it filters and orders by when fetching.
        $this->addSql('CREATE INDEX idx_failed_messages_queue_name_available_at_delivered_at_id ON failed_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE failed_messages');
    }
}
