<?php

declare(strict_types=1);

namespace App\Tests\Integration;

use App\Auth\Application\Command\Passkey\RegisterPasskeyCommand;
use App\Auth\Application\CommandHandler\Passkey\RegisterPasskeyHandler;
use App\Auth\Domain\Event\Passkey\PasskeyRegistered;
use App\Auth\Infrastructure\Doctrine\Entity\PasskeyEntity;
use App\Auth\Infrastructure\Doctrine\Entity\UserEntity;
use App\Auth\Infrastructure\Doctrine\UserRepository;
use App\Auth\Infrastructure\Repository\Passkey\PasskeyRepository;
use App\Shared\Domain\Event\Outbox\OutboxRepository;
use App\Shared\Domain\Event\Outbox\OutboxSubscriber;
use App\Shared\Infrastructure\Doctrine\DoctrineTransaction;
use App\Shared\Infrastructure\Doctrine\Platform\BaanderDriverMiddleware;
use App\Shared\Infrastructure\Doctrine\Type\CustomTypesRegistrar;
use App\Shared\Domain\Model\PublicId;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Tools\DsnParser;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\UnderscoreNamingStrategy;
use Doctrine\ORM\ORMSetup;
use Doctrine\ORM\Tools\SchemaTool;
use Doctrine\Persistence\ManagerRegistry;
use PHPUnit\Framework\TestCase;
use Psr\Log\NullLogger;
use SwooleBundle\SwooleBundle\Bridge\Swoole\Swoole;
use Symfony\Component\EventDispatcher\EventDispatcher;

final class PasskeyRegistrationOutboxTransactionTest extends TestCase
{
    private Connection $writer;
    private Connection $observer;
    private EntityManager $manager;
    private string $schema;

    protected function setUp(): void
    {
        CustomTypesRegistrar::register();
        $url = getenv('OUTBOX_TEST_DATABASE_URL');
        if (!$url) {
            self::markTestSkipped('Set OUTBOX_TEST_DATABASE_URL to a disposable PostgreSQL database.');
        }
        $params = (new DsnParser(['postgresql' => 'pdo_pgsql']))->parse($url);
        $dbal = new Configuration();
        $dbal->setMiddlewares([new BaanderDriverMiddleware()]);
        $this->writer = DriverManager::getConnection($params, $dbal);
        $this->observer = DriverManager::getConnection($params, $dbal);
        $this->schema = 'passkey_outbox_' . bin2hex(random_bytes(8));
        $this->writer->executeStatement('CREATE SCHEMA ' . $this->schema);
        foreach ([$this->writer, $this->observer] as $connection) {
            $connection->executeStatement('SET search_path TO ' . $this->schema . ', public');
        }

        $orm = ORMSetup::createAttributeMetadataConfig([dirname(__DIR__, 2) . '/src'], isDevMode: true);
        $orm->setNamingStrategy(new UnderscoreNamingStrategy());
        $orm->enableNativeLazyObjects(true);
        $this->manager = new EntityManager($this->writer, $orm);
        (new SchemaTool($this->manager))->createSchema(array_map(
            $this->manager->getClassMetadata(...),
            [UserEntity::class, PasskeyEntity::class],
        ));
        $this->writer->executeStatement(<<<'SQL'
            CREATE TABLE domain_event_outbox (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_class TEXT NOT NULL,
                event_name TEXT NOT NULL,
                payload JSONB NOT NULL,
                created_at TIMESTAMPTZ NOT NULL,
                relayed_at TIMESTAMPTZ,
                attempts INTEGER NOT NULL DEFAULT 0,
                next_attempt_at TIMESTAMPTZ,
                dead_lettered_at TIMESTAMPTZ
            )
            SQL);
    }

    protected function tearDown(): void
    {
        if (isset($this->writer)) {
            if ($this->writer->isTransactionActive()) {
                $this->writer->rollBack();
            }
            if (isset($this->schema)) {
                $this->writer->executeStatement('DROP SCHEMA ' . $this->schema . ' CASCADE');
            }
            $this->writer->close();
        }
        if (isset($this->observer)) {
            $this->observer->close();
        }
    }

    public function testOutboxFailureRollsBackCredentialThenRetryPersistsMatchingIdentityAndEvent(): void
    {
        $userEntity = new UserEntity(new PublicId(), 'Passkey owner', 'passkey-owner@baander.app', 'unused', '');
        $this->manager->persist($userEntity);
        $this->manager->flush();
        $userId = $userEntity->getId();
        $users = new UserRepository($this->manager);
        $passkeys = new PasskeyRepository($this->manager);
        $outbox = new OutboxRepository($this->writer);
        $events = new EventDispatcher();
        $events->addListener(PasskeyRegistered::class, new OutboxSubscriber($outbox, new NullLogger()));

        $this->writer->executeStatement(<<<'SQL'
            CREATE FUNCTION reject_outbox_event() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'rejected outbox event';
            END
            $$
            SQL);
        $this->writer->executeStatement(<<<'SQL'
            CREATE TRIGGER reject_outbox_event
            BEFORE INSERT ON domain_event_outbox
            FOR EACH ROW EXECUTE FUNCTION reject_outbox_event()
            SQL);

        try {
            $this->handler($users, $passkeys, $events)(new RegisterPasskeyCommand(
                $userId->toString(), 'Laptop', 'credential-a', ['credential' => 'key-material'], 0,
            ));
            self::fail('Outbox insertion failure must abort passkey registration.');
        } catch (\Throwable $error) {
            self::assertStringContainsString('rejected outbox event', $error->getMessage());
        }

        self::assertSame(0, (int) $this->observer->fetchOne('SELECT COUNT(*) FROM passkeys'));
        self::assertSame(0, (int) $this->observer->fetchOne('SELECT COUNT(*) FROM domain_event_outbox'));

        $this->writer->executeStatement('DROP TRIGGER reject_outbox_event ON domain_event_outbox');
        $this->writer->executeStatement('DROP FUNCTION reject_outbox_event()');
        $this->manager->clear();
        $passkey = $this->handler($users, $passkeys, $events)(new RegisterPasskeyCommand(
            $userId->toString(), 'Laptop', 'credential-a', ['credential' => 'key-material'], 0,
        ));

        self::assertSame(1, (int) $this->observer->fetchOne('SELECT COUNT(*) FROM passkeys'));
        self::assertSame(1, (int) $this->observer->fetchOne('SELECT COUNT(*) FROM domain_event_outbox'));
        self::assertSame(
            $passkey->getId()->toString(),
            $this->observer->fetchOne('SELECT id::text FROM passkeys'),
        );
        $payloadJson = (string) $this->observer->fetchOne(
            'SELECT payload::text FROM domain_event_outbox',
        );
        $payload = json_decode($payloadJson, true, flags: JSON_THROW_ON_ERROR);
        self::assertSame($passkey->getId()->toString(), $payload['passkey_id']);
    }

    private function handler(
        UserRepository $users,
        PasskeyRepository $passkeys,
        EventDispatcher $events,
    ): RegisterPasskeyHandler {
        $registry = $this->createStub(ManagerRegistry::class);
        $registry->method('getManager')->willReturn($this->manager);

        return new RegisterPasskeyHandler(
            $users,
            $passkeys,
            $events,
            new DoctrineTransaction($registry, new Swoole()),
        );
    }
}
