/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "auth.login": [],
    "auth.refreshToken": [],
    "auth.register": [],
    "auth.tokens": [],
    "auth.tokens.revoke": [
        {
            "name": "token",
            "required": true
        }
    ],
    "auth.tokens.revokeAll": [],
    "auth.forgotPassword": [],
    "auth.resetPassword": [],
    "auth.verifyEmail": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "auth.logout": [],
    "oauth.clients.index": [],
    "oauth.clients.store": [],
    "oauth.clients.show": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "oauth.clients.update": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "oauth.clients.destroy": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "oauth.clients.regenerate-secret": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "oauth.authorize": [],
    "oauth.token": [],
    "oauth.device.authorize": [],
    "oauth.device.verify": [],
    "oauth.device.approve": [],
    "oauth.introspect": [],
    "api.job.locks": [],
    "api.job.lock": [
        {
            "name": "jobClass",
            "required": true
        },
        {
            "name": "jobId",
            "required": true
        }
    ],
    "api.job.lock-delete": [
        {
            "name": "jobClass",
            "required": true
        },
        {
            "name": "jobId",
            "required": true
        }
    ],
    "api.job.cleanup": [],
    "api.job.failed-cleanup": [],
    "api.job.library-scan": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "api.albums.index": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.albums.show": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "album",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.albums.update": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "album",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.artists.index": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.artists.show": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "artist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.artists.update": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "artist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.genres.index": [],
    "api.genres.show": [
        {
            "name": "genre",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.genres.update": [
        {
            "name": "genre",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.genres.destroy": [
        {
            "name": "genre",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.libraries.index": [],
    "api.library.create": [],
    "api.library.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "api.library.update": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "api.library.delete": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "api.metadata.browse.albums": [],
    "api.metadata.browse.artists": [],
    "api.metadata.browse.songs": [],
    "api.metadata.browse.lookup": [
        {
            "name": "source",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "api.metadata.browse.apply": [],
    "api.metadata.search.album": [
        {
            "name": "album",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.metadata.search-fuzzy.album": [
        {
            "name": "album",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.metadata.sync": [],
    "api.metadata.stats": [
        {
            "name": "libraryId",
            "required": true
        }
    ],
    "api.metadata.validate": [],
    "api.movies.index": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.movies.show": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "movie",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.index": [],
    "api.playlist.store": [],
    "api.playlist.show": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.destroy": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.add-song": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "song",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.remove-song": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "song",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.update": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.reorder": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.collaborators.store": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.collaborators.destroy": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.clone": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.statistics": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.statistics.record-view": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.statistics.record-play": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.statistics.record-share": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.statistics.record-favorite": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.smart-create": [],
    "api.playlist.smart-update": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.playlist.smart-sync": [
        {
            "name": "playlist",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.songs.index": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.songs.show": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "publicId",
            "required": true
        }
    ],
    "api.songs.update": [
        {
            "name": "library",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "song",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.logs.index": [],
    "api.logs.show": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.content": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.lines": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.tail": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.head": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.stats": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.search": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.download": [
        {
            "name": "logFile",
            "required": true
        }
    ],
    "api.logs.search-all": [],
    "api.image.serve": [
        {
            "name": "image",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.stream.song-direct": [
        {
            "name": "song",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.opcache.getConfig": [],
    "api.opcache.clear": [],
    "api.opcache.compile": [],
    "api.queue-metrics.show": [],
    "api.queue-metrics.queues": [],
    "api.queue-metrics.metrics": [],
    "api.queue-metrics.retry-job": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.queue-metrics.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.queue-metrics.purge": [],
    "lastfm.authorize": [],
    "lastfm.callback": [],
    "lastfm.disconnect": [],
    "lastfm.status": [],
    "spotify.authorize": [],
    "spotify.callback": [],
    "spotify.disconnect": [],
    "spotify.status": [],
    "spotify.user.profile": [],
    "spotify.user.playlists": [],
    "spotify.search": [],
    "spotify.genres.seeds": [],
    "api.system-info.php": [],
    "api.system-info.sys": [],
    "api.users.index": [],
    "api.users.store": [],
    "api.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.users.me": [],
    "api.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.user-tokens.index": [
        {
            "name": "user",
            "required": true
        }
    ],
    "api.user-tokens.revoke": [
        {
            "name": "token",
            "required": true
        }
    ],
    "auth.passkey.options": [],
    "auth.passkey.login": [],
    "auth.passkey.register-option": [],
    "auth.passkey.register": [],
    "mailbook.dashboard": [],
    "mailbook.content": [],
    "mailbook.send": [],
    "ui.docs-get": [],
    "webui": [
        {
            "name": "any",
            "required": true
        }
    ],
    "scramble.docs.document": [],
    "scramble.docs.ui": []
}
}
export {};
