<?php

declare(strict_types=1);

use App\Auth\Application\Command\User\CreateUserCommand;
use App\Auth\Application\Command\User\RegisterUserCommand;
use App\Auth\Application\Command\User\VerifyEmailCommand;
use App\Auth\Infrastructure\Doctrine\Entity\EmailVerificationTokenEntity;
use App\Auth\Infrastructure\Doctrine\Entity\UserEntity;
use App\Notification\Infrastructure\Doctrine\Entity\NotificationPreferenceEntity;
use App\Shared\Domain\Model\Email;
use App\Shared\Infrastructure\Doctrine\Entity\JobMonitorEntity;
use Doctrine\DBAL\DriverManager;
use Doctrine\ORM\Tools\SchemaTool;

require dirname(__DIR__, 2) . '/vendor/autoload.php';
(new Symfony\Component\Dotenv\Dotenv())->bootEnv(dirname(__DIR__, 2) . '/.env');

$kernel = new App\Kernel('prod', false);
$kernel->boot();
$em = $kernel->getContainer()->get('doctrine')->getManager();
$db = $em->getConnection();
// Observe committed state independently of Doctrine's connection and identity map.
$observer = DriverManager::getConnection($db->getParams());
$bus = $kernel->getContainer()->get('messenger.default_bus');

$assertCount = static function (string $sql, int $expected, array $params = []) use ($observer): void {
    $actual = (int) $observer->fetchOne($sql, $params);
    if ($actual !== $expected) {
        throw new RuntimeException(sprintf('Expected %d, got %d: %s', $expected, $actual, $sql));
    }
};
$expectConstraintFailure = static function (object $command, string $constraint) use ($bus): void {
    try {
        $bus->dispatch($command);
    } catch (Throwable $error) {
        do {
            if ($error instanceof Doctrine\DBAL\Exception\DriverException
                && $error->getSQLState() === '23514'
                && str_contains($error->getMessage(), $constraint)) {
                return;
            }
            $error = $error->getPrevious();
        } while ($error !== null);
        throw new RuntimeException('Expected PostgreSQL CHECK failure: ' . $constraint);
    }
    throw new RuntimeException('Expected dispatch to fail: ' . $constraint);
};
$rejectEvent = static function (string $eventName) use ($observer): void {
    $observer->executeStatement('ALTER TABLE domain_event_outbox ADD CONSTRAINT producer_reject_event CHECK (event_name <> '
        . $observer->quote($eventName) . ') NOT VALID');
};
$allowEvents = static function () use ($observer): void {
    $observer->executeStatement('ALTER TABLE domain_event_outbox DROP CONSTRAINT producer_reject_event');
};
$assertUserState = static function (string $email, int $users, int $tokens, int $preferences) use ($assertCount): void {
    $assertCount('SELECT COUNT(*) FROM users WHERE email = ?', $users, [$email]);
    $assertCount('SELECT COUNT(*) FROM email_verification_tokens t JOIN users u ON u.id = t.user_id WHERE u.email = ?', $tokens, [$email]);
    $assertCount('SELECT COUNT(*) FROM notification_preferences p JOIN users u ON u.id = p.user_id WHERE u.email = ?', $preferences, [$email]);
};

try {
    $db->executeStatement('CREATE EXTENSION IF NOT EXISTS citext');
    // Preserve production mappings, including their inherited timezone-free datetime types.
    (new SchemaTool($em))->createSchema(array_map($em->getClassMetadata(...), [
        UserEntity::class, EmailVerificationTokenEntity::class,
        NotificationPreferenceEntity::class, JobMonitorEntity::class,
    ]));
    $db->executeStatement('CREATE TABLE domain_event_outbox (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_class TEXT NOT NULL, event_name TEXT NOT NULL, payload JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL, relayed_at TIMESTAMPTZ,
        attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at TIMESTAMPTZ,
        dead_lettered_at TIMESTAMPTZ, lease_token TEXT, lease_until TIMESTAMPTZ
    )');

    $registerEmail = 'producer-register@baander.app';
    $register = new RegisterUserCommand(Email::fromString($registerEmail), 'Producer Registration', 'Test-password-42');
    $rejectEvent('user.registered');
    $expectConstraintFailure($register, 'producer_reject_event');
    $assertUserState($registerEmail, 0, 0, 0);
    $assertCount('SELECT COUNT(*) FROM domain_event_outbox', 0);
    $allowEvents();
    $bus->dispatch($register);
    $assertUserState($registerEmail, 1, 1, 12);
    $assertCount("SELECT COUNT(*) FROM domain_event_outbox WHERE event_name = 'user.registered'", 1);
    echo "Registration rolls back user, token, preferences, and outbox; same-bus retry commits all four.\n";

    $token = (string) $observer->fetchOne('SELECT t.token FROM email_verification_tokens t JOIN users u ON u.id = t.user_id WHERE u.email = ?', [$registerEmail]);
    $verify = new VerifyEmailCommand($token);
    $rejectEvent('user.email_verified');
    $expectConstraintFailure($verify, 'producer_reject_event');
    $assertCount('SELECT COUNT(*) FROM users WHERE email = ? AND email_verified_at IS NULL', 1, [$registerEmail]);
    $assertCount('SELECT COUNT(*) FROM email_verification_tokens WHERE token = ? AND used_at IS NULL', 1, [$token]);
    $assertCount("SELECT COUNT(*) FROM domain_event_outbox WHERE event_name = 'user.email_verified'", 0);
    $allowEvents();
    $bus->dispatch($verify);
    $assertCount('SELECT COUNT(*) FROM users WHERE email = ? AND email_verified_at IS NOT NULL', 1, [$registerEmail]);
    $assertUserState($registerEmail, 1, 0, 12);
    $assertCount("SELECT COUNT(*) FROM domain_event_outbox WHERE event_name = 'user.email_verified'", 1);
    echo "Verification rollback retains an unused token and unverified user; same-bus retry consumes the token and commits the event.\n";

    $createEmail = 'producer-create@baander.app';
    $create = new CreateUserCommand(Email::fromString($createEmail), 'Producer Operator', 'Test-password-42', ['ROLE_USER']);
    $rejectEvent('user.created_by_operator');
    $expectConstraintFailure($create, 'producer_reject_event');
    $assertUserState($createEmail, 0, 0, 0);
    $assertCount("SELECT COUNT(*) FROM domain_event_outbox WHERE event_name = 'user.created_by_operator'", 0);
    $allowEvents();
    $bus->dispatch($create);
    $assertUserState($createEmail, 1, 0, 12);
    $assertCount("SELECT COUNT(*) FROM domain_event_outbox WHERE event_name = 'user.created_by_operator'", 1);
    echo "Operator creation rolls back user, preferences, and outbox; same-bus retry commits them.\n";

    // ORM flush errors close the manager, unlike the DBAL outbox failures above.
    $flushEmail = 'producer-flush@baander.app';
    $flushRegister = new RegisterUserCommand(Email::fromString($flushEmail), 'Producer Flush', 'Test-password-42');
    $observer->executeStatement("ALTER TABLE users ADD CONSTRAINT producer_reject_user CHECK (email <> 'producer-flush@baander.app') NOT VALID");
    $expectConstraintFailure($flushRegister, 'producer_reject_user');
    $assertUserState($flushEmail, 0, 0, 0);
    $assertCount('SELECT COUNT(*) FROM domain_event_outbox', 3);
    $observer->executeStatement('ALTER TABLE users DROP CONSTRAINT producer_reject_user');
    $bus->dispatch($flushRegister);
    $assertUserState($flushEmail, 1, 1, 12);
    $assertCount('SELECT COUNT(*) FROM domain_event_outbox', 4);
    echo "ORM flush failure rolls back and same-bus retry recovers a closed manager.\n";
} finally {
    $observer->close();
    $kernel->shutdown();
}
