<?php

namespace App\Http\Integrations\MusicBrainz\Models;

use Spatie\LaravelData\Data;

class IsrcList extends Data
{
    public function __construct(public mixed $count, public mixed $offset, public mixed $isrc, public mixed $id, public mixed $recording, public mixed $title, public mixed $length, public mixed $annotation, public mixed $text, public mixed $type, public mixed $entity, public mixed $name, public mixed $disambiguation, public mixed $video, public mixed $artist_credit, public mixed $first_release_date, public mixed $release, public mixed $status, public mixed $quality, public mixed $packaging, public mixed $text_representation, public mixed $language, public mixed $script, public mixed $alias, public mixed $locale, public mixed $sort_name, public mixed $type_id, public mixed $primary, public mixed $begin_date, public mixed $end_date, public mixed $release_group, public mixed $primary_type, public mixed $secondary_type, public mixed $tag, public mixed $user_tag, public mixed $genre, public mixed $target_type, public mixed $relation, public mixed $target, public mixed $ordering_key, public mixed $direction, public mixed $begin, public mixed $end, public mixed $ended, public mixed $source_credit, public mixed $target_credit, public mixed $user_genre, public mixed $rating, public mixed $votes_count, public mixed $user_rating, public mixed $date, public mixed $country, public mixed $release_event, public mixed $area, public mixed $iso_3166_1_code, public mixed $iso_3166_2_code, public mixed $iso_3166_3_code, public mixed $life_span, public mixed $barcode, public mixed $asin, public mixed $cover_art_archive, public mixed $artwork, public mixed $front, public mixed $back, public mixed $darkened, public mixed $label_info, public mixed $catalog_number, public mixed $label, public mixed $label_code, public mixed $ipi, public mixed $isni, public mixed $track_count, public mixed $medium, public mixed $track, public mixed $position, public mixed $number, public mixed $format, public mixed $disc, public mixed $sectors, public mixed $pregap, public mixed $collection, public mixed $entity_type, public mixed $editor, public mixed $artist, public mixed $gender, public mixed $begin_area, public mixed $end_area, public mixed $work, public mixed $fluency, public mixed $iswc, public mixed $event, public mixed $cancelled, public mixed $time, public mixed $setlist, public mixed $instrument, public mixed $description, public mixed $place, public mixed $address, public mixed $coordinates, public mixed $latitude, public mixed $longitude, public mixed $series, public mixed $puid)
    {
    }

    public static function fromApiData(array $data): self
    {
        return new self(
            count: $data['count'] ?? null,
            offset: $data['offset'] ?? null,
            isrc: $data['isrc'] ?? null,
            id: $data['id'] ?? null,
            recording: $data['recording'] ?? null,
            title: $data['title'] ?? null,
            length: $data['length'] ?? null,
            annotation: $data['annotation'] ?? null,
            text: $data['text'] ?? null,
            type: $data['type'] ?? null,
            entity: $data['entity'] ?? null,
            name: $data['name'] ?? null,
            disambiguation: $data['disambiguation'] ?? null,
            video: $data['video'] ?? null,
            artist_credit: $data['artist-credit'] ?? null,
            first_release_date: $data['first-release-date'] ?? null,
            release: $data['release'] ?? null,
            status: $data['status'] ?? null,
            quality: $data['quality'] ?? null,
            packaging: $data['packaging'] ?? null,
            text_representation: $data['text-representation'] ?? null,
            language: $data['language'] ?? null,
            script: $data['script'] ?? null,
            alias: $data['alias'] ?? null,
            locale: $data['locale'] ?? null,
            sort_name: $data['sort-name'] ?? null,
            type_id: $data['type-id'] ?? null,
            primary: $data['primary'] ?? null,
            begin_date: $data['begin-date'] ?? null,
            end_date: $data['end-date'] ?? null,
            release_group: $data['release-group'] ?? null,
            primary_type: $data['primary-type'] ?? null,
            secondary_type: $data['secondary-type'] ?? null,
            tag: $data['tag'] ?? null,
            user_tag: $data['user-tag'] ?? null,
            genre: $data['genre'] ?? null,
            target_type: $data['target-type'] ?? null,
            relation: $data['relation'] ?? null,
            target: $data['target'] ?? null,
            ordering_key: $data['ordering-key'] ?? null,
            direction: $data['direction'] ?? null,
            begin: $data['begin'] ?? null,
            end: $data['end'] ?? null,
            ended: $data['ended'] ?? null,
            source_credit: $data['source-credit'] ?? null,
            target_credit: $data['target-credit'] ?? null,
            user_genre: $data['user-genre'] ?? null,
            rating: $data['rating'] ?? null,
            votes_count: $data['votes-count'] ?? null,
            user_rating: $data['user-rating'] ?? null,
            date: $data['date'] ?? null,
            country: $data['country'] ?? null,
            release_event: $data['release-event'] ?? null,
            area: $data['area'] ?? null,
            iso_3166_1_code: $data['iso-3166-1-code'] ?? null,
            iso_3166_2_code: $data['iso-3166-2-code'] ?? null,
            iso_3166_3_code: $data['iso-3166-3-code'] ?? null,
            life_span: $data['life-span'] ?? null,
            barcode: $data['barcode'] ?? null,
            asin: $data['asin'] ?? null,
            cover_art_archive: $data['cover-art-archive'] ?? null,
            artwork: $data['artwork'] ?? null,
            front: $data['front'] ?? null,
            back: $data['back'] ?? null,
            darkened: $data['darkened'] ?? null,
            label_info: $data['label-info'] ?? null,
            catalog_number: $data['catalog-number'] ?? null,
            label: $data['label'] ?? null,
            label_code: $data['label-code'] ?? null,
            ipi: $data['ipi'] ?? null,
            isni: $data['isni'] ?? null,
            track_count: $data['track-count'] ?? null,
            medium: $data['medium'] ?? null,
            track: $data['track'] ?? null,
            position: $data['position'] ?? null,
            number: $data['number'] ?? null,
            format: $data['format'] ?? null,
            disc: $data['disc'] ?? null,
            sectors: $data['sectors'] ?? null,
            pregap: $data['pregap'] ?? null,
            collection: $data['collection'] ?? null,
            entity_type: $data['entity-type'] ?? null,
            editor: $data['editor'] ?? null,
            artist: $data['artist'] ?? null,
            gender: $data['gender'] ?? null,
            begin_area: $data['begin-area'] ?? null,
            end_area: $data['end-area'] ?? null,
            work: $data['work'] ?? null,
            fluency: $data['fluency'] ?? null,
            iswc: $data['iswc'] ?? null,
            event: $data['event'] ?? null,
            cancelled: $data['cancelled'] ?? null,
            time: $data['time'] ?? null,
            setlist: $data['setlist'] ?? null,
            instrument: $data['instrument'] ?? null,
            description: $data['description'] ?? null,
            place: $data['place'] ?? null,
            address: $data['address'] ?? null,
            coordinates: $data['coordinates'] ?? null,
            latitude: $data['latitude'] ?? null,
            longitude: $data['longitude'] ?? null,
            series: $data['series'] ?? null,
            puid: $data['puid'] ?? null
        );
    }
}