<?php

namespace App\Http\Integrations\MusicBrainz\Models;

use Spatie\LaravelData\Data;

class Release extends Data
{
    public function __construct(
        public ?int $release,
        public ?string $id,
        public ?string $title,
        public ?string $status,
        public ?string $quality,
        public ?string $annotation,
        public ?string $text,
        public ?string $type,
        public ?string $entity,
        public ?string $name,
        public ?string $disambiguation,
        public ?string $packaging,
        public ?array $text_representation,
        public ?string $language,
        public ?string $script,
        public ?array $artist_credit,
        public ?int $count,
        public ?int $offset,
        public ?array $alias,
        public ?string $locale,
        public ?string $sort_name,
        public ?string $type_id,
        public ?bool $primary,
        public ?string $begin_date,
        public ?string $end_date,
        public ?array $release_group,
        public ?string $first_release_date,
        public ?string $primary_type,
        public ?array $secondary_type,
        public ?string $date,
        public ?string $country,
        public ?array $release_event,
        public ?array $area,
        public ?string $iso_3166_1_code,
        public ?string $iso_3166_2_code,
        public ?string $iso_3166_3_code,
        public ?array $life_span,
        public ?string $begin,
        public ?string $end,
        public ?bool $ended,
        public ?array $tag,
        public ?array $user_tag,
        public ?array $genre,
        public ?string $target_type,
        public ?array $relation,
        public ?string $target,
        public ?int $ordering_key,
        public ?string $direction,
        public ?string $source_credit,
        public ?string $target_credit,
        public ?array $user_genre,
        public ?string $barcode,
        public ?string $asin,
        public ?array $cover_art_archive,
        public ?bool $artwork,
        public ?bool $front,
        public ?bool $back,
        public ?bool $darkened,
        public ?array $label_info,
        public ?string $catalog_number,
        public ?array $label,
        public ?string $label_code,
        public ?array $ipi,
        public ?array $isni,
        public ?array $rating,
        public ?int $votes_count,
        public ?int $user_rating,
        public ?int $track_count,
        public ?array $medium,
        public ?array $track,
        public ?int $position,
        public ?string $number,
        public ?int $length,
        public ?array $recording,
        public ?bool $video,
        public ?array $puid,
        public ?array $isrc,
        public ?array $format,
        public ?array $disc,
        public ?int $sectors,
        public ?int $pregap,
        public ?array $collection,
        public ?string $entity_type,
        public ?string $editor,
        public ?array $artist,
        public ?string $gender,
        public ?array $begin_area,
        public ?array $end_area,
        public ?array $work,
        public ?string $fluency,
        public ?array $iswc,
        public ?array $event,
        public ?bool $cancelled,
        public ?string $time,
        public ?array $setlist,
        public ?array $instrument,
        public ?string $description,
        public ?array $place,
        public ?string $address,
        public ?array $coordinates,
        public ?float $latitude,
        public ?float $longitude,
        public ?array $series,
        public ?array $media,
        public ?int $score
    ) {
    }

    public static function fromApiData(array $data): self
    {
        return new self(
            release: $data['release'] ?? null,
            id: $data['id'] ?? null,
            title: $data['title'] ?? null,
            status: $data['status'] ?? null,
            quality: $data['quality'] ?? null,
            annotation: $data['annotation'] ?? null,
            text: $data['text'] ?? null,
            type: $data['type'] ?? null,
            entity: $data['entity'] ?? null,
            name: $data['name'] ?? null,
            disambiguation: $data['disambiguation'] ?? null,
            packaging: $data['packaging'] ?? null,
            text_representation: $data['text-representation'] ?? null,
            language: $data['language'] ?? null,
            script: $data['script'] ?? null,
            artist_credit: $data['artist-credit'] ?? null,
            count: isset($data['count']) ? (int)$data['count'] : null,
            offset: isset($data['offset']) ? (int)$data['offset'] : null,
            alias: $data['alias'] ?? null,
            locale: $data['locale'] ?? null,
            sort_name: $data['sort-name'] ?? null,
            type_id: $data['type-id'] ?? null,
            primary: isset($data['primary']) ? (bool)$data['primary'] : null,
            begin_date: $data['begin-date'] ?? null,
            end_date: $data['end-date'] ?? null,
            release_group: $data['release-group'] ?? null,
            first_release_date: $data['first-release-date'] ?? null,
            primary_type: $data['primary-type'] ?? null,
            secondary_type: $data['secondary-type'] ?? null,
            date: $data['date'] ?? null,
            country: $data['country'] ?? null,
            release_event: $data['release-event'] ?? null,
            area: $data['area'] ?? null,
            iso_3166_1_code: $data['iso-3166-1-code'] ?? null,
            iso_3166_2_code: $data['iso-3166-2-code'] ?? null,
            iso_3166_3_code: $data['iso-3166-3-code'] ?? null,
            life_span: $data['life-span'] ?? null,
            begin: $data['begin'] ?? null,
            end: $data['end'] ?? null,
            ended: isset($data['ended']) ? (bool)$data['ended'] : null,
            tag: $data['tag'] ?? null,
            user_tag: $data['user-tag'] ?? null,
            genre: $data['genre'] ?? null,
            target_type: $data['target-type'] ?? null,
            relation: $data['relation'] ?? null,
            target: $data['target'] ?? null,
            ordering_key: isset($data['ordering-key']) ? (int)$data['ordering-key'] : null,
            direction: $data['direction'] ?? null,
            source_credit: $data['source-credit'] ?? null,
            target_credit: $data['target-credit'] ?? null,
            user_genre: $data['user-genre'] ?? null,
            barcode: $data['barcode'] ?? null,
            asin: $data['asin'] ?? null,
            cover_art_archive: $data['cover-art-archive'] ?? null,
            artwork: isset($data['artwork']) ? (bool)$data['artwork'] : null,
            front: isset($data['front']) ? (bool)$data['front'] : null,
            back: isset($data['back']) ? (bool)$data['back'] : null,
            darkened: isset($data['darkened']) ? (bool)$data['darkened'] : null,
            label_info: $data['label-info'] ?? null,
            catalog_number: $data['catalog-number'] ?? null,
            label: $data['label'] ?? null,
            label_code: $data['label-code'] ?? null,
            ipi: $data['ipi'] ?? null,
            isni: $data['isni'] ?? null,
            rating: $data['rating'] ?? null,
            votes_count: isset($data['votes-count']) ? (int)$data['votes-count'] : null,
            user_rating: isset($data['user-rating']) ? (int)$data['user-rating'] : null,
            track_count: isset($data['track-count']) ? (int)$data['track-count'] : null,
            medium: $data['medium'] ?? null,
            track: $data['track'] ?? null,
            position: isset($data['position']) ? (int)$data['position'] : null,
            number: $data['number'] ?? null,
            length: isset($data['length']) ? (int)$data['length'] : null,
            recording: $data['recording'] ?? null,
            video: isset($data['video']) ? (bool)$data['video'] : null,
            puid: $data['puid'] ?? null,
            isrc: $data['isrc'] ?? null,
            format: $data['format'] ?? null,
            disc: $data['disc'] ?? null,
            sectors: isset($data['sectors']) ? (int)$data['sectors'] : null,
            pregap: isset($data['pregap']) ? (int)$data['pregap'] : null,
            collection: $data['collection'] ?? null,
            entity_type: $data['entity-type'] ?? null,
            editor: $data['editor'] ?? null,
            artist: $data['artist'] ?? null,
            gender: $data['gender'] ?? null,
            begin_area: $data['begin-area'] ?? null,
            end_area: $data['end-area'] ?? null,
            work: $data['work'] ?? null,
            fluency: $data['fluency'] ?? null,
            iswc: $data['iswc'] ?? null,
            event: $data['event'] ?? null,
            cancelled: isset($data['cancelled']) ? (bool)$data['cancelled'] : null,
            time: $data['time'] ?? null,
            setlist: $data['setlist'] ?? null,
            instrument: $data['instrument'] ?? null,
            description: $data['description'] ?? null,
            place: $data['place'] ?? null,
            address: $data['address'] ?? null,
            coordinates: $data['coordinates'] ?? null,
            latitude: isset($data['latitude']) ? (float)$data['latitude'] : null,
            longitude: isset($data['longitude']) ? (float)$data['longitude'] : null,
            series: $data['series'] ?? null,
            media: $data['media'] ?? null,
            score: isset($data['score']) ? (int)$data['score'] : null
        );
    }
}