name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Qodana Scan with Auto-fixes'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
          apply-fixes: true
          push-fixes: commit
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1066393617 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      - name: 'Commit auto-fixes'
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name 'Qodana Auto-fix'
          git config --global user.email 'qodana@jetbrains.com'
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-fix code quality issues"
            git push
          fi